### PR TITLE
feat: add google analytics

### LINKED ISSUE #10: add google analytics

### PR DESCRIPTION
**Pull request by hasanagh**
adds google analytics

closes #10

### CODE REVIEW

**Comment by hasanagh** [comment]
@juancarlosfarah  the [gatsby google analytics plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/) has some cool options that I think you might like. What do you think?

for example:
- head
- anonymize
- respectDNT

**Comment by hasanagh** [comment]
@juancarlosfarah  Also regarding the default environment variables files in gatsby, they would be `.env.development` and `.env.production`

**Comment by juancarlosfarah** [comment]
@hasanagh, yes, let's go for the recommended options. For the names of the env variables. Is it hard to change to `.prod` and `.dev`? Otherwise, go with the defaults.

**Review by juancarlosfarah — APPROVED** [review]

**Comment by juancarlosfarah** [comment]
@hasanagh, can you also coordinate with @hagoptaminian to implement this for `graasp-org`? Should be the same code. Thanks!

**Comment by hasanagh** [comment]
@juancarlosfarah Sure!, yes definitely it's the same code. I will open an issue there

**Pull request merged**
